import movieOne from '../images/plugs/pic__COLOR_pic-1.jpg';
import movieTwo from '../images/plugs/pic__COLOR_pic-2.jpg';
import movieThree from '../images/plugs/pic__COLOR_pic-3.jpg';
import movieFour from '../images/plugs/pic__COLOR_pic-4.jpg';
import movieFive from '../images/plugs/pic__COLOR_pic-5.jpg';
import movieSix from '../images/plugs/pic__COLOR_pic-6.jpg';
import movieSeven from '../images/plugs/pic__COLOR_pic-7.jpg';
import movieEight from '../images/plugs/pic__COLOR_pic-8.jpg';
import movieNine from '../images/plugs/pic__COLOR_pic-9.jpg';
import movieTen from '../images/plugs/pic__COLOR_pic-10.jpg';
import movieEleven from '../images/plugs/pic__COLOR_pic-11.jpg';
import movieTwelve from '../images/plugs/pic__COLOR_pic-12.jpg';


const moviesList = [
  {
    country: '',
    director: '',
    duration: 102,
    year: '',
    description: '',
    image: movieOne,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 1,
    nameRU: '33 слова о дизайне',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 95,
    year: '',
    description: '',
    image: movieTwo,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 2,
    nameRU: 'Киноальманах «100 лет дизайна»',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 42,
    year: '',
    description: '',
    image: movieThree,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 3,
    nameRU: 'В погоне за Бенкси',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 126,
    year: '',
    description: '',
    image: movieFour,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 4,
    nameRU: 'Баския: Взрыв реальности',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 72,
    year: '',
    description: '',
    image: movieFive,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 5,
    nameRU: 'Бег это свобода',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 15,
    year: '',
    description: '',
    image: movieSix,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 6,
    nameRU: 'Книготорговцы',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 98,
    year: '',
    description: '',
    image: movieSeven,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 7,
    nameRU: 'Когда я думаю о Германии ночью',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 24,
    year: '',
    description: '',
    image: movieEight,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 8,
    nameRU: 'Gimme Danger: История Игги и The Stooges',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 69,
    year: '',
    description: '',
    image: movieNine,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 9,
    nameRU: 'Дженис: Маленькая девочка грустит',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 83,
    year: '',
    description: '',
    image: movieTen,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 10,
    nameRU: 'Соберись перед прыжком',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 115,
    year: '',
    description: '',
    image: movieEleven,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 11,
    nameRU: 'Пи Джей Харви: A dog called money',
    nameEN: '',
  },
  {
    country: '',
    director: '',
    duration: 123,
    year: '',
    description: '',
    image: movieTwelve,
    trailerLink: '',
    thumbnail: '',
    owner: '',
    movieId: 12,
    nameRU: 'По волнам: Искусство звука в кино',
    nameEN: '',
  },
]

export { moviesList };